### PR TITLE
Feature/separate class files

### PR DESCRIPTION
**Pull request by omarst9**
* Separated the deploy_stack file into multiple smaller files for improved readability and maintainability. The classes are grouped based on similar functionality, so the S3, lambda and cfn classes have their own files.
* Moved the ```examples``` folder to the root of the project
* Fixed a couple of issues in kms-parameters-lambda.cf.yaml and dev.yaml

### CODE REVIEW

**Comment by abukharov** [comment]
Structure looks about right. Only one thing: I would avoid the word 'classes' in the filenames. Can you pls call them like `cfn_stack.py`, `cfn_stackset.py` and so on.

**Comment by abukharov** [comment]
Ah, one more. The idea of having `examples` inside the package was that when you install it from pypi you get the examples as well. Otherwise they will not get packaged or end up outside the package directory.

**Comment by hamidnazari** [comment]
I think this is a good start, there's no need for `_class` and `_classes` suffixes. Is there? 
I may need one or two more iterations until it's nicely structured.
e.g.
- `CloudformationEnvironment` can be moved out of `deploy_stack.py`.
- `deploy_stack.py` can match its main class' name, `stack_deployer.py`.
- `deploy_stack` directory can be called `cloudformation_seed`.
- All CloudFormation related classes can either be package in a separate dir, or in one file. It's going to be a little long, but it'll be flat and consistent with the rest of the file structure.
- I'm sure there's more, e.g. `s = boto3.Session()` is util class, can we called it a `session` at least?

**Comment by omarst9** [comment]
I've renamed all the files and removed ```_class``` and ```_classes```, renamed the ```deploy_stack``` file and folder and fixed the example makefiles

**Pull request merged**
